backend:
  name: git-gateway
  repo: AwareErmine/The_Radish
  branch: main

# Run the command below to use
# npx netlify-cms-proxy-server
local_backend: true

media_folder: /static/assets
public_folder: /assets

collections:
  - name: "issue"
    label: "Issue"
    folder: "content/issues"
    create: true
    fields:
      - name: "cover"
        label: "Cover image"
        widget: "image"
        default: "/static/assets/radimir-rootin.png"
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "PDF url", name: "pdf", widget: "string" }

  - name: "article"
    label: "Article"
    folder: "content/articles"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - label: "Author"
            name: "author"
            widget: "relation"
            collection: "author"
            search_fields: ["title", "position"]
            value_field: "title"
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - label: "Tag"
            name: "tag"
            widget: "relation"
            collection: "tag"
            search_fields: ["title"]
            value_field: "title"
      - label: "Issue"
        name: "issue"
        widget: "relation"
        collection: "issue"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]

  - name: "author"
    label: "Author"
    folder: "content/authors"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Position",
          name: "position",
          widget: "string",
          default: "writer",
        }
      - { label: "Grad year", name: "date", widget: "string" }

  - name: "tag"
    label: "Tag"
    folder: "content/tags"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Color"
        name: "color"
        widget: "select"
        options: ["red", "orange", "yellow", "green", "blue", "purple", "white", "black"]
