backend:
  name: git-gateway
  repo: AwareErmine/The_Radish
  branch: main

media_folder: static/assets
# public_folder: /assets

collections:
  - name: 'article'
    label: 'Articles'
    folder: 'content/article'
    create: true
    # slug: 'index'
    # media_folder: ''
    # public_folder: ''
    # path: '{{title}}/index'
    # editor:
    #   preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Issue url', name: 'issue', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: Authors
        name: authors
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Position, name: position, widget: string}

# Search for an author
# {
#   allMarkdownRemark(
#     filter:{
#       frontmatter:{
#         authors: {elemMatch: {name: {eq: "Aramie Ewen"}}}
#       }
#     }
# ) {
#     edges {
#       node {
#         frontmatter {
#           authors {
#             name
#             position
#           }
#         }
#       }
#     }
#   }
# }
